<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="3" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-10T00:25:58 IST" name="Suite" finished-at="2022-11-10T00:26:24 IST" duration-ms="25972">
    <groups>
      <group name="ErrorHandeling">
        <method signature="ErrorValidations.LoginErrorValidation()[pri:0, instance:Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations@1a4927d6]" name="LoginErrorValidation" class="Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations"/>
      </group> <!-- ErrorHandeling -->
    </groups>
    <test started-at="2022-11-10T00:25:58 IST" name="Submit Order Test" finished-at="2022-11-10T00:25:58 IST" duration-ms="26">
    </test> <!-- Submit Order Test -->
    <test started-at="2022-11-10T00:25:58 IST" name="Error Validation Test" finished-at="2022-11-10T00:26:24 IST" duration-ms="25559">
      <class name="Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations@1a4927d6]" started-at="2022-11-10T00:25:58 IST" name="launchApplication" finished-at="2022-11-10T00:26:03 IST" duration-ms="5046" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations@1a4927d6]" started-at="2022-11-10T00:26:03 IST" name="LoginErrorValidation" finished-at="2022-11-10T00:26:04 IST" duration-ms="1045" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations.LoginErrorValidation(ErrorValidations.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations@1a4927d6]" started-at="2022-11-10T00:26:04 IST" name="tearDown" finished-at="2022-11-10T00:26:04 IST" duration-ms="65" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations@1a4927d6]" started-at="2022-11-10T00:26:04 IST" name="launchApplication" finished-at="2022-11-10T00:26:06 IST" duration-ms="1944" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations@1a4927d6]" started-at="2022-11-10T00:26:06 IST" name="LoginErrorValidation" finished-at="2022-11-10T00:26:07 IST" duration-ms="857" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations.LoginErrorValidation(ErrorValidations.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations@1a4927d6]" started-at="2022-11-10T00:26:07 IST" name="tearDown" finished-at="2022-11-10T00:26:24 IST" duration-ms="16258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Ratul.SeleniumTestNGFrameworkDesign.ErrorValidations -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
